language: node_js
node_js:
  - 10
  - 12
  - 14
cache:
  directories:
    - "node_modules"
before_install:
  - wget https://www.antlr.org/download/antlr-4.13.2-complete.jar --directory-prefix typeonly
# before_script:
#   - npm run build
env:
  - SUB_PROJECT=typeonly
  - SUB_PROJECT=loader
  - SUB_PROJECT=validator
  - SUB_PROJECT=validator-cli
script: cd $SUB_PROJECT && npm i && npm run prepublishOnly
